name: Deploy production

on:
    push:
        tags:
            - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Login to docker hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Tags docker image
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ secrets.DOCKER_USERNAME }}/moneykeeper-client

            - name: Build and push to docker hub
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}

            - name: Start SSH agent
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  script: |
                      cd /www/wwwroot/money-keeper-client/domain1/money-keeper-client-1
                      git config --global --add safe.directory /www/wwwroot/money-keeper-client/domain1/money-keeper-client-1
                      sudo git pull origin main
                      docker pull ${{ steps.meta.outputs.tags }}
                      docker compose up -d
